In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
train=pd.read_csv("C:/Users/chlal/Documents/DATA/train.csv")
test=pd.read_csv("C:/Users/chlal/Documents/DATA/test.csv")
sub=pd.read_csv("C:/Users/chlal/Documents/DATA/sample_submission.csv")
age=pd.read_csv("C:/Users/chlal/Documents/DATA/age_gender_info.csv")

train.shape , test.shape , sub.shape , age.shape

((2952, 15), (1022, 14), (150, 2), (16, 23))

In [5]:
train.columns

Index(['단지코드', '총세대수', '임대건물구분', '지역', '공급유형', '전용면적', '전용면적별세대수', '공가수',
       '자격유형', '임대보증금', '임대료', '도보 10분거리 내 지하철역 수(환승노선 수 반영)',
       '도보 10분거리 내 버스정류장 수', '단지내주차면수', '등록차량수'],
      dtype='object')

In [6]:
train.isnull().sum()

단지코드                              0
총세대수                              0
임대건물구분                            0
지역                                0
공급유형                              0
전용면적                              0
전용면적별세대수                          0
공가수                               0
자격유형                              0
임대보증금                           569
임대료                             569
도보 10분거리 내 지하철역 수(환승노선 수 반영)    211
도보 10분거리 내 버스정류장 수                4
단지내주차면수                           0
등록차량수                             0
dtype: int64

In [39]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2952 entries, 0 to 2951
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   단지코드                          2952 non-null   object
 1   총세대수                          2952 non-null   int64
 2   임대건물구분                        2952 non-null   object
 3   지역                            2952 non-null   object
 4   공급유형                          2952 non-null   object
 5   전용면적                          2952 non-null   float64
 6   전용면적별세대수                      2952 non-null   int64
 7   공가수                           2952 non-null   float64
 8   자격유형                          2952 non-null   object
 9   임대보증금                         2383 non-null   object
 10  임대료                           2383 non-null   object
 11  도보 10분거리 내 지하철역 수(환승노선 수 반영)  2741 non-null   float64
 12  도보 10분거리 내 버스정류장 수            2948 non-null   float64
 13  단지내주차면수                       2952 non-null   float64
 14  등록차량수                         2952 non-null   float64
dtypes: float64(6), int64(2), object(7)
memory usage: 346.1+ KB

In [40]:
sel = ['총세대수','전용면적별세대수','전용면적','공가수']

X = train[sel]
y = train['등록차량수']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
pred

array([ 517.02862677,  770.03283574,  601.9058644 ,  507.97282962,
        530.71666949,  414.99336959,  494.26597033,  368.1934519 ,
        546.3911954 ,  744.28808797,  667.80060764,  721.1715678 ,
        564.29096917,  604.77836543,  822.8963934 ,  390.06355872,
        899.88115696,  574.01695445,  680.97548894,  536.5613728 ,
        354.19262841,  513.61186923,  607.85967042,  493.67778737,
        243.89037633,  602.58534564,  732.68476049,  688.81240465,
        455.9127274 ,  572.46477058,  611.75058153,  607.8646914 ,
        563.14902426,  432.52142558,  377.5808843 ,  423.60545338,
        593.81500681,  788.94214896,  740.47331434,  647.83882244,
        377.66124523,  421.49086371,  420.35589988,  614.25378725,
        590.35465573,  735.22182357,  619.67723243,  384.27278129,
        513.24663677,  483.04680771,  438.54327632,  496.92496952,
        549.33891851,  380.66366851,  515.76880334,  581.16024425,
        559.0542277 ,  359.27839907,  553.18146344,  489.55105211,
        641.93155005,  635.93305002,  673.28049846,  375.26995829,
        437.41968378,  614.87222879,  715.55582822,  597.96041628,
        627.0708969 ,  582.94881983,  354.68540615,  531.18917176,
        541.07677959,  814.59974525,  324.12781008,  622.15847024,
        410.93940523,  448.60897939,  475.98557419,  424.89540894,
       1665.54258161,  526.89744373,  592.44918447,  801.80430821,
        726.40563878,  418.45896257,  448.68617478,  575.94413996,
        448.18155006,  568.17825407,  706.00458595,  348.62294456,
        706.3934472 ,  448.34685705,  614.17170346,  600.48772386,
        640.30999891,  465.58485681,  612.37774898,  712.50335153,
        546.96993802,  341.56090824, 1033.64887161,  590.30520417,
        434.8502798 ,  407.67010571,  578.59394267,  508.79437188,
        320.96487289,  833.57244433,  314.67762011,  541.42202892,
        593.31161326,  549.60574699,  406.53892739,  443.97238538,
        899.81406441,  393.84192408,  368.1934519 ,  752.72164101,
        433.99981289,  639.25725604,  338.75847183,  685.39131842,
        855.8881584 ,  452.48902586,  782.34523867,  406.68621521,
        479.32526687,  831.13272822,  534.84645813,  512.26530622,
        624.24468717, 1029.839743  ,  582.64138903,  390.84478612,
        707.11709515,  627.92705597,  575.14440757,  505.02555629,
        643.23632176,  292.1653403 ,  576.92474507,  409.77528885,
        538.07917675,  688.81240465,  628.71212553,  514.12075986,
        403.80473226,  607.67253794,  721.35386252,  388.9062105 ,
       1204.00413592,  406.68621521,  506.67834346,  856.38067797,
        794.5661866 ,  540.90261963, 1020.80531783,  582.90817932,
        526.89744373,  641.75659396,  589.78902493,  430.22696734,
        424.83592806,  641.13038701,  366.82033273,  572.36041445,
        522.91667653,  441.58984489,  406.13968425,  597.35957858,
        529.01834482,  414.99336959,  476.28684774,  505.81476108,
        709.8657145 , 1414.56784903,  422.78520298,  683.31897897,
        640.21445968,  700.45174853,  514.70189074,  643.41444819,
        587.5289028 ,  500.72834333,  421.47436843,  483.80821116,
        795.14232974,  360.27566725,  413.84544313,  425.18459749,
        443.1094002 ,  531.93268733,  364.21807161,  539.99170774,
        411.41003716,  653.39430403,  749.57438525,  415.47197559,
        473.42271131,  726.13409307,  860.43007586,  366.87994261,
       1003.94276586,  793.92415429,  469.00802616,  398.82720209,
        493.11922457,  712.21273915,  635.27629503,  736.44396768,
        578.17304004,  737.83022428,  861.60166394,  391.85481777,
        580.70681205,  436.90104047,  602.52873141,  331.25588621,
        818.84483969,  474.33476882,  710.62720594,  413.02769082,
        621.40761639,  721.07870656,  353.05263191,  532.50589334,
        452.67182476,  454.37574725,  546.40440723,  893.15525872,
        493.84088272,  370.10014226,  410.99906171,  430.95027937,
        467.94710654,  457.69672648,  475.98557419,  632.09725799,
        603.61101149,  430.58498193,  618.46164544,  559.40853257,
        880.44567926,  529.18424885,  931.94534836,  473.10956442,
       1065.12809617,  892.51314884,  328.34169763,  558.89229821,
        654.81755817,  682.40175888,  628.15921114,  505.99129065,
        601.18493513,  700.24047687,  439.02198574,  647.60308489,
        539.86498824,  377.46517594,  285.40300328,  407.85259641,
        427.99610789,  492.19661844,  672.05821065,  471.58088213,
        462.48111406,  672.4319034 ,  429.97542668,  345.78412046,
       1107.03505609,  349.56310871,  663.14834184, 1110.83160804,
        650.23590819,  490.51248828,  656.52606628,  633.8965099 ,
        792.30403121,  474.24411843,  450.9131572 ,  901.9326227 ,
        402.78070924,  477.39859431,  436.46721914,  609.75857556,
        603.72654692,  431.63111572,  917.64897582,  383.58693443,
        528.82335677,  346.18166358,  453.16039154,  748.37288058,
        850.77039048,  478.18281739,  540.41104251,  419.95369646,
        463.93444153,  616.15889787,  577.1959517 ,  734.05327632,
        358.43358963,  345.06336339,  724.56844083,  385.36772231,
        702.29667641,  496.41252937,  685.82969087,  619.07372931,
        623.71744321,  529.44726389,  503.77949173,  438.20245424,
        572.24284333,  378.38800842,  483.01122283,  358.29041137,
        531.53894842,  553.67928969,  667.62341193,  592.7253299 ,
        574.39561053,  511.67432625,  524.91610077,  724.56844083,
        721.55717992,  476.07229716,  523.78445066,  237.9771642 ,
        581.07664356,  505.11536628,  464.74704639,  765.15706403,
        406.53892739,  611.30600197,  600.87884845, 1509.79571122,
        421.24450377,  535.750201  ,  394.38138833,  439.64020811,
        605.94203235,  397.93370058,  519.79842018,  611.37937689,
        507.32222368,  377.70226384,  613.63272083,  601.18842952,
        785.32283255,  454.45912156,  487.45089684,  651.57071004,
        446.09549267,  508.76767866,  434.44796745,  722.43614259,
        759.53345269,  582.89877408,  612.57449671,  558.66998369,
        406.68621521,  440.83764463,  815.46767751,  830.19719798,
        744.09766098,  739.83805657,  536.72498447,  479.36075482,
        443.92967877,  602.95982315,  484.5621371 ,  483.90708325,
        568.3742976 ,  550.21036994,  671.332767  ,  454.38670107,
        388.59617759,  357.21602591,  380.22625905,  427.75356658,
        687.12224853,  705.62150253,  399.94186607,  554.12371701,
        623.12841355,  379.6537258 ,  418.51334933,  860.59516943,
        349.86754545, 1096.48818102,  468.77236248,  527.70456785,
        435.14307174,  543.07580188,  661.44848534,  543.84087549,
        528.1397382 ,  526.89744373,  657.36951232,  439.81187817,
        521.89574007,  597.8086529 ,  454.42822142,  612.12953183,
        349.99514931,  537.74229673,  481.32531683,  478.8803531 ,
        806.28383785,  568.1154367 ,  433.94533584,  573.35001791,
        692.15244121,  411.89747112,  652.67629821,  432.7260705 ,
        877.5355338 ,  728.39152076,  830.21795236,  329.18256694,
        577.65105374,  633.88501712,  495.67612409,  739.83805657,
        751.93960479,  715.14130631,  596.3103906 ,  470.23798233,
        782.62878893,  615.36690575,  199.30209433,  547.66703526,
        732.87209612,  638.45476797,  319.82333205,  690.34002687,
        525.31314655,  966.12456242,  563.90714848,  406.68621521,
        396.55023218,  669.48483782,  383.21965417,  410.25593383,
        334.85716291,  591.12979231,  469.04776084,  465.968615  ,
        478.74729277,  591.56067692,  691.43284504,  487.86558262,
        625.93868989,  440.5681624 ,  569.42889128,  425.47703739,
        469.7632383 ,  522.40010989,  378.45779448,  440.6379586 ,
        822.23601912,  349.86754545,  781.69737296,  650.58786776,
        456.57805889,  791.90066625,  710.63148862,  900.80221519,
        873.71433051,  989.39780309,  486.76764919,  702.47382043,
        473.12469386,  448.10922639,  290.85027992,  722.970955  ,
        497.87433449,  463.33911382,  702.79221482,  503.33936225,
        439.79658248,  368.1934519 ,  850.93359563,  660.85405153,
        514.15490219,  832.58429355,  404.52465585,  528.97028523,
        676.74795753,  851.19661319,  406.68621521,  528.97028523,
        602.68993895,  473.78685971,  318.55668616,  434.45130024,
        752.39996465,  574.39561053,  799.81112884,  670.95434229,
        371.31045911,  561.07498364,  451.73507559,  699.80440517,
        377.12229105,  361.42042018,  630.2728078 ,  447.86294119,
        861.41822664,  822.67626864,  471.31796396, 1414.56784903,
        404.18557675,  597.08383535,  514.58862388,  377.5808843 ,
        380.42553023,  479.91638646,  591.68554424,  627.51098703,
        728.38872685,  613.74571808,  799.76494973,  687.90440944,
        530.54617674,  381.61012802,  733.70675637,  579.70855748,
        437.43509398,  403.54726988,  811.11706767,  799.77555601,
        269.89227177,  431.96558042,  330.68723058,  722.34442394,
        456.84169412,  733.09827533,  440.58225873,  501.00120887,
        591.69239656,  381.12578163,  572.66364555, 1093.4572055 ,
        615.83329142,  468.77236248,  869.88599082,  586.73682543,
        364.08016635, 1033.60992074,  355.0660479 ,  544.0731266 ,
        447.34841781, 1090.01805174,  442.83557699,  356.89640145,
        453.47000443,  657.37092874,  203.16137829,  349.86754545,
        480.58566456,  733.38485457,  772.32773096,  231.06449109,
        435.4028587 ,  377.5808843 ,  419.6882895 ,  518.26833766,
        818.84483969,  769.31207794,  698.935344  ,  471.58553293,
        532.37689639,  325.7774854 ,  719.89659852,  386.56339003,
        595.99553874,  369.20335106,  368.1934519 ,  406.68621521,
        516.22577668,  757.26099993,  679.03635423,  507.62445105,
        491.0944588 ,  369.00057603,  462.29352121,  505.34315368,
        404.36273026,  470.39675134,  607.21351861,  616.67163914,
        427.90507083,  658.66180028,  480.93881253,  541.06092581,
        859.00027576,  577.96530839,  540.76954531,  566.28768182,
        511.30743483,  577.53682889,  401.98941917,  526.89744373,
        681.01470295,  429.93977075,  559.02940643,  630.72220213,
        601.54375099,  563.66005277,  482.62065526,  415.27988836,
        483.58579873,  391.83122465,  757.07460399,  783.54033871,
        449.35064176,  622.33486191,  801.26586743,  861.41822664,
        436.76557472,  446.06757877,  603.68438641,  449.11234564,
        472.53653169,  406.53892739,  429.53828043,  472.53798418,
        464.94064714,  637.75317301,  479.99232284,  449.51863896,
        472.51870413,  495.25065143,  598.22126136,  720.44110155,
        420.99304616,  473.3531884 ,  407.88937056,  685.39131842,
        861.24052472,  455.63604575,  516.98028029,  545.31472835,
        406.68621521,  992.76174489,  752.13732052,  581.43418486,
        479.43702961,  720.44110155,  945.49739588,  851.49952733,
        713.51348482,  457.81293039,  438.23358191,  822.8963934 ,
        431.95908678,  470.23492064,  896.18789224,  606.21666691,
        379.6537258 ,  316.94255357,  435.12393004,  606.05072759,
        538.75852714,  530.77252591,  556.00329834,  792.10562956,
        710.36630358,  598.08034035,  491.48602614,  530.41224053,
        647.11130458,  642.6319045 ,  613.89410197,  756.68844318,
        861.58332021,  501.06023102,  465.25607143,  345.06336339,
        345.06336339,  590.35465573,  501.76505819,  448.22073859,
        682.07455591,  447.21049259,  633.0182728 ,  665.13201829,
        602.95982315,  539.67280131,  413.86279785,  361.9887137 ,
        584.97994281,  637.66941443,  714.55730746,  450.83683622,
        352.55905243, 1021.21297863,  706.28223177,  611.21428332,
        433.99981289,  362.81682623,  463.7580098 ,  518.98026859,
        557.69210495,  528.97028523, 1114.54651793, 1381.57256367,
        533.61304267,  495.90330874,  484.23266118,  629.60867714,
        372.45361986,  407.89259737,  401.03440917,  610.68603095,
        520.96520468,  478.4720187 ,  423.47812323,  500.30009968,
        572.52934231,  453.03181751,  410.33220872,  952.67534957,
        389.45650451,  692.85189049,  844.14550354,  752.90507831,
        487.57394216,  547.11792931,  960.46218125,  706.00458595,
        641.59150039,  377.72631461])

In [43]:
dict_dat = {"실제값":y_test, "예측값":pred,
            "오차":y_test -  pred, "오차절대값" : abs(y_test-pred),
            "오차제곱":(y_test -  pred)**2}
dat = pd.DataFrame(dict_dat)
dat

         실제값         예측값          오차       오차절대값           오차제곱
1301  1158.0  517.028627  640.971373  640.971373  410844.301295
2788  1400.0  770.032836  629.967164  629.967164  396858.628041
2286   982.0  601.905864  380.094136  380.094136  144471.551917
2668   854.0  507.972830  346.027170  346.027170  119734.802642
1934   614.0  530.716669   83.283331   83.283331    6936.113141
...      ...         ...         ...         ...            ...
2754   568.0  547.117929   20.882071   20.882071     436.060877
1850  1044.0  960.462181   83.537819   83.537819    6978.567161
581    172.0  706.004586 -534.004586  534.004586  285160.897819
459    364.0  641.591500 -277.591500  277.591500   77057.041089
1074   328.0  377.726315  -49.726315   49.726315    2472.706365

[738 rows x 5 columns]

In [44]:
for i in range(1, 6, 1):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(i/10), random_state=42)

    model = LinearRegression()
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    pred[:5]
    
    mae = np.abs(y_test - pred).sum() / len(pred)
    mse = ((y_test - pred)**2).sum()/len(pred)
    rmse = (((y_test - pred)**2).sum()/len(pred))**0.5
    
    print("test_size : ",(i/10))
    print("MAE : {:.3f}".format(mae))
    print("MSE : {:.3f}".format(mse))
    print("RMSE : {:.3f}".format(rmse))
    print("")

test_size :  0.1
MAE : 284.839
MSE : 151581.859
RMSE : 389.335

test_size :  0.2
MAE : 293.437
MSE : 157958.919
RMSE : 397.440

test_size :  0.3
MAE : 290.277
MSE : 158224.875
RMSE : 397.775

test_size :  0.4
MAE : 290.733
MSE : 164242.667
RMSE : 405.269

test_size :  0.5
MAE : 289.608
MSE : 164297.461
RMSE : 405.336